# Generated by Django 2.2.2 on 2019-06-18 02:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regiao', models.TextField()),
                ('bairro', models.TextField()),
                ('descricao', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('kml', models.FileField(upload_to='uploads/')),
                ('dwg', models.FileField(upload_to='uploads/')),
                ('pdf', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
