# Generated by Django 2.2.2 on 2019-06-18 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomarabaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados',
            name='bairro',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dados',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dados',
            name='regiao',
            field=models.CharField(max_length=200),
        ),
    ]
